import {
  Home,
  CalendarRange,
  ListChecks,
  TrendingUp,
  NotebookPen,
  AlertCircle,
  Sparkles,
  Settings,
  MessageCircle,
  MoreHorizontal,
  LogOut,
  X,
  ShieldCheck,
  Users,
  ClipboardList,
  FileCheck2,
  BookOpen,
  Building2,
  ChevronDown,
  ChevronRight,
  Clock,
  GraduationCap,
  School,
  UserRound,
  Undo2,
  Library,
} from 'lucide-react'

const ICONS = {
  Home,
  CalendarRange,
  ListChecks,
  TrendingUp,
  NotebookPen,
  AlertCircle,
  Sparkles,
  Settings,
  MessageCircle,
  MoreHorizontal,
  LogOut,
  X,
  ShieldCheck,
  Users,
  ClipboardList,
  FileCheck2,
  BookOpen,
  Building2,
  ChevronDown,
  ChevronRight,
  Clock,
  GraduationCap,
  School,
  UserRound,
  Undo2,
  Library,
}

export default function NavIcon({ name, size = 20, className }) {
  const Icon = ICONS[name] || Sparkles
  return <Icon size={size} className={className} aria-hidden="true" />
}
