import { BookOpen, Check, GraduationCap, UserRound } from 'lucide-react'

export function ChildProfilePreview() {
  return <><div className="rp-summary"><strong>Çocuklarım → Profil oluştur</strong><small>Çocuğuna ait çalışma alanını hazırla</small></div><div className="rp-profile-avatar"><UserRound size={28} aria-hidden="true" /><span><strong>Ece</strong><small>Öğrenci profili</small></span></div><dl className="rp-profile-fields"><div><dt>Adı soyadı</dt><dd>Ece Yılmaz</dd></div><div><dt>Sınıf</dt><dd>8. sınıf</dd></div><div><dt>Okul</dt><dd>Örnek Ortaokulu</dd></div></dl><div className="rp-assignment"><strong><Check size={14} aria-hidden="true" /> Çocuk profili hazır</strong><span>Sıradaki adım: Ece’nin kullandığı kaynakları ekle.</span></div><div className="rp-callout">Her çocuğun kitaplığı, görevleri ve gelişimi kendi profili altında takip edilir.</div></>
}

export function ParentBooksPreview() {
  return <><div className="rp-summary"><strong>Kitaplık → Kütüphaneden kitap seç</strong><small>Ece · 8. sınıf kaynakları</small></div><div className="rp-library-picks">{['Matematik Soru Bankası', 'Türkçe Soru Bankası', 'Fen Bilimleri Soru Bankası'].map((book, i) => <div key={book}><span className={`rp-mini-cover cover-${i}`}><BookOpen size={19} aria-hidden="true" /><b>8</b></span><span><strong>{book}</strong><small>Konu ve testleriyle kitaplıkta</small></span><Check size={16} aria-label="Seçildi" /></div>)}</div><div className="rp-assignment"><strong>Aradığın kaynak kütüphanede yok mu?</strong><span>Yeni Kitap Ekle ile kendi kaynağını oluştur veya kapak, içindekiler ve cevap anahtarıyla kitap ekleme talebi gönder.</span></div></>
}

export function PastResultsPreview() {
  return <><div className="rp-summary"><strong>Kitaplık → Matematik → Test 1</strong><small>Daha önce kitaptan çözülmüş test · 5 soru</small></div><div className="rp-past-answers"><span>Soru</span>{[1, 2, 3, 4, 5].map(n => <b key={n}>{n}</b>)}<span>Cevap</span>{['A', 'C', 'D', 'B', 'C'].map((answer, i) => <strong key={i} className={i === 3 ? 'wrong' : ''}>{answer}</strong>)}</div><div className="rp-result-strip"><span><b>4</b>Doğru</span><span><b>1</b>Yanlış</span><span><b>0</b>Boş</span></div><div className="rp-assignment"><strong>Kaydet · Geçmiş test sonucu</strong><span>Çocuğunun kitaptaki cevaplarını gir; önceki emeği de kayda geçsin.</span></div><div className="rp-callout">Bu örnekte 10 testlik kaynağın ilk testi kaydedildi:<br /><strong>%10 tamamlanma · %80 başarı</strong></div><p className="rp-small-note">Cevap anahtarı varsa optik cevap girişi; yoksa doğru, yanlış ve boş sayılarıyla kayıt.</p></>
}

export function ParentBookMetricsPreview() {
  return <><div className="rp-person">E <span><strong>Ece · Matematik Soru Bankası</strong><small>Girilen geçmiş sonuçlar artık kitaplıkta</small></span></div><div className="rp-parent-metrics"><div><strong>%10</strong><b>Tamamlanma</b><small>1 / 10 test kaydedildi</small><span><i style={{width:'10%'}} /></span></div><div><strong>%80</strong><b>Başarı</b><small>5 sorunun 4’ü doğru</small><span><i style={{width:'80%'}} /></span></div></div><div className="rp-table"><div><strong>Kaydedilen test</strong><strong>D / Y / B</strong><strong>Durum</strong></div><div><span>Test 1</span><span>4 / 1 / 0</span><span>Tamamlandı</span></div></div><div className="rp-callout"><strong>İki oran, iki ayrı bilgi.</strong><br />Tamamlanma: kitapta ne kadar ilerledi?<br />Başarı: çözdüğü sorularda ne kadar doğru yaptı?</div><div className="rp-assignment"><strong>Sıradaki adım: kalan testleri planla</strong><span>Geçmiş çalışmalar kaydedildikçe mevcut durum netleşir.</span></div></>
}

export function ParentAssignmentPreview() {
  return <><div className="rp-summary"><strong>Haftalık Plan → Gün seç → Görev ekle</strong><small>Ece için sıradaki çalışmayı planla</small></div><dl className="rp-profile-fields"><div><dt>Kaynak</dt><dd>Matematik Soru Bankası</dd></div><div><dt>Çalışma</dt><dd>Test 2 · 5 soru</dd></div><div><dt>Gün / saat</dt><dd>Salı · 17.30</dd></div></dl><div className="rp-week-days rp-assignment-days">{['Pzt', 'Sal', 'Çar', 'Per', 'Cum', 'Cmt', 'Paz'].map(day => <span key={day} className={day === 'Sal' ? 'selected' : ''}>{day}<b>{day === 'Sal' ? '●' : '·'}</b></span>)}</div><div className="rp-assignment"><strong><Check size={14} aria-hidden="true" /> Görev haftalık plana eklendi</strong><span>Salı 17.30 · Test 2, Ece’nin Bugün ekranında görünecek.</span></div><div className="rp-callout">Okul ve ders saatlerine göre uygun zamanı seç; günlük görevlerle haftanın planını oluştur.</div></>
}

export function ParentTeachersPreview() {
  return <><div className="rp-summary"><strong>Çocuklarım → Öğretmenler</strong><small>İsteğe bağlı · Özel ders öğretmeni varsa</small></div><div className="rp-profile-avatar"><GraduationCap size={28} aria-hidden="true" /><span><strong>Ayşe Öğretmen</strong><small>Matematik · Özel ders</small></span></div><dl className="rp-profile-fields"><div><dt>Öğrenci</dt><dd>Ece Yılmaz</dd></div><div><dt>Takip edeceği kaynak</dt><dd>Matematik Soru Bankası</dd></div><div><dt>Panel erişimi</dt><dd>Takip yetkisi verildi</dd></div></dl><div className="rp-assignment"><strong>Çocuk + kaynak + öğretmen eşleşti</strong><span>Öğretmen kendi panelinden ilgili çalışmaları ve sonuçları takip edebilir.</span></div><div className="rp-callout">Özel öğretmen yoksa bu adımı atla. Planlama ve gelişim takibini kendin sürdürebilirsin.</div></>
}

export function ParentFollowupPreview() {
  return <><div className="rp-summary"><strong>Bugün → Ece’nin görevleri</strong><small>Planlanan çalışmanın sonucunu takip et</small></div><div className="rp-task-card"><div className="rp-task-top"><span>Salı · 17.30</span><span>Tamamlandı</span></div><h5>Matematik · Test 2</h5><p>Matematik Soru Bankası · 5 soru</p><div className="rp-result-strip"><span><b>3</b>Doğru</span><span><b>1</b>Yanlış</span><span><b>1</b>Boş</span></div></div><div className="rp-parent-metrics"><div><strong>%20</strong><b>Kitap tamamlanması</b><small>2 / 10 test</small></div><div><strong>%70</strong><b>Kaynak başarısı</b><small>Toplam 10 soruda 7 doğru</small></div></div><div className="rp-callout">Geçmiş Test 1 + yeni görev Test 2:<br />Kitabın ilerlemesi ve başarısı aynı kayıtlar üzerinden takip edilir.</div><div className="rp-assignment"><strong>Sıradaki bakış: yanlışlar ve gelişim</strong><span>Hangi konuda desteğe ihtiyaç olduğunu sonuçlar üzerinden incele.</span></div></>
}
