-- Generated by api/scripts/generate-geo-seed.js — do not hand-edit district lists here, regenerate instead.
-- Turkish province/district reference data. District boundaries are occasionally reorganized by law;
-- treat this as best-effort accurate, not a guaranteed-authoritative source.

INSERT INTO dbo.Provinces (name, plate_code) VALUES
    (N'Adana', 1),
    (N'Adıyaman', 2),
    (N'Afyonkarahisar', 3),
    (N'Ağrı', 4),
    (N'Amasya', 5),
    (N'Ankara', 6),
    (N'Antalya', 7),
    (N'Artvin', 8),
    (N'Aydın', 9),
    (N'Balıkesir', 10),
    (N'Bilecik', 11),
    (N'Bingöl', 12),
    (N'Bitlis', 13),
    (N'Bolu', 14),
    (N'Burdur', 15),
    (N'Bursa', 16),
    (N'Çanakkale', 17),
    (N'Çankırı', 18),
    (N'Çorum', 19),
    (N'Denizli', 20),
    (N'Diyarbakır', 21),
    (N'Edirne', 22),
    (N'Elazığ', 23),
    (N'Erzincan', 24),
    (N'Erzurum', 25),
    (N'Eskişehir', 26),
    (N'Gaziantep', 27),
    (N'Giresun', 28),
    (N'Gümüşhane', 29),
    (N'Hakkari', 30),
    (N'Hatay', 31),
    (N'Isparta', 32),
    (N'Mersin', 33),
    (N'İstanbul', 34),
    (N'İzmir', 35),
    (N'Kars', 36),
    (N'Kastamonu', 37),
    (N'Kayseri', 38),
    (N'Kırklareli', 39),
    (N'Kırşehir', 40),
    (N'Kocaeli', 41),
    (N'Konya', 42),
    (N'Kütahya', 43),
    (N'Malatya', 44),
    (N'Manisa', 45),
    (N'Kahramanmaraş', 46),
    (N'Mardin', 47),
    (N'Muğla', 48),
    (N'Muş', 49),
    (N'Nevşehir', 50),
    (N'Niğde', 51),
    (N'Ordu', 52),
    (N'Rize', 53),
    (N'Sakarya', 54),
    (N'Samsun', 55),
    (N'Siirt', 56),
    (N'Sinop', 57),
    (N'Sivas', 58),
    (N'Tekirdağ', 59),
    (N'Tokat', 60),
    (N'Trabzon', 61),
    (N'Tunceli', 62),
    (N'Şanlıurfa', 63),
    (N'Uşak', 64),
    (N'Van', 65),
    (N'Yozgat', 66),
    (N'Zonguldak', 67),
    (N'Aksaray', 68),
    (N'Bayburt', 69),
    (N'Karaman', 70),
    (N'Kırıkkale', 71),
    (N'Batman', 72),
    (N'Şırnak', 73),
    (N'Bartın', 74),
    (N'Ardahan', 75),
    (N'Iğdır', 76),
    (N'Yalova', 77),
    (N'Karabük', 78),
    (N'Kilis', 79),
    (N'Osmaniye', 80),
    (N'Düzce', 81);
GO

-- 1 Adana
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 1);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Aladağ'),
    (@provinceId, N'Ceyhan'),
    (@provinceId, N'Çukurova'),
    (@provinceId, N'Feke'),
    (@provinceId, N'İmamoğlu'),
    (@provinceId, N'Karaisalı'),
    (@provinceId, N'Karataş'),
    (@provinceId, N'Kozan'),
    (@provinceId, N'Pozantı'),
    (@provinceId, N'Saimbeyli'),
    (@provinceId, N'Sarıçam'),
    (@provinceId, N'Seyhan'),
    (@provinceId, N'Tufanbeyli'),
    (@provinceId, N'Yumurtalık'),
    (@provinceId, N'Yüreğir');
GO

-- 2 Adıyaman
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 2);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Merkez'),
    (@provinceId, N'Besni'),
    (@provinceId, N'Çelikhan'),
    (@provinceId, N'Gerger'),
    (@provinceId, N'Gölbaşı'),
    (@provinceId, N'Kahta'),
    (@provinceId, N'Samsat'),
    (@provinceId, N'Sincik'),
    (@provinceId, N'Tut');
GO

-- 3 Afyonkarahisar
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 3);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Merkez'),
    (@provinceId, N'Başmakçı'),
    (@provinceId, N'Bayat'),
    (@provinceId, N'Bolvadin'),
    (@provinceId, N'Çay'),
    (@provinceId, N'Çobanlar'),
    (@provinceId, N'Dazkırı'),
    (@provinceId, N'Dinar'),
    (@provinceId, N'Emirdağ'),
    (@provinceId, N'Evciler'),
    (@provinceId, N'Hocalar'),
    (@provinceId, N'İhsaniye'),
    (@provinceId, N'İscehisar'),
    (@provinceId, N'Kızılören'),
    (@provinceId, N'Sandıklı'),
    (@provinceId, N'Sinanpaşa'),
    (@provinceId, N'Sultandağı'),
    (@provinceId, N'Şuhut');
GO

-- 4 Ağrı
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 4);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Merkez'),
    (@provinceId, N'Diyadin'),
    (@provinceId, N'Doğubayazıt'),
    (@provinceId, N'Eleşkirt'),
    (@provinceId, N'Hamur'),
    (@provinceId, N'Patnos'),
    (@provinceId, N'Taşlıçay'),
    (@provinceId, N'Tutak');
GO

-- 5 Amasya
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 5);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Merkez'),
    (@provinceId, N'Göynücek'),
    (@provinceId, N'Gümüşhacıköy'),
    (@provinceId, N'Hamamözü'),
    (@provinceId, N'Merzifon'),
    (@provinceId, N'Suluova'),
    (@provinceId, N'Taşova');
GO

-- 6 Ankara
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 6);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Akyurt'),
    (@provinceId, N'Altındağ'),
    (@provinceId, N'Ayaş'),
    (@provinceId, N'Bala'),
    (@provinceId, N'Beypazarı'),
    (@provinceId, N'Çamlıdere'),
    (@provinceId, N'Çankaya'),
    (@provinceId, N'Çubuk'),
    (@provinceId, N'Elmadağ'),
    (@provinceId, N'Etimesgut'),
    (@provinceId, N'Evren'),
    (@provinceId, N'Gölbaşı'),
    (@provinceId, N'Güdül'),
    (@provinceId, N'Haymana'),
    (@provinceId, N'Kalecik'),
    (@provinceId, N'Kahramankazan'),
    (@provinceId, N'Keçiören'),
    (@provinceId, N'Kızılcahamam'),
    (@provinceId, N'Mamak'),
    (@provinceId, N'Nallıhan'),
    (@provinceId, N'Polatlı'),
    (@provinceId, N'Pursaklar'),
    (@provinceId, N'Sincan'),
    (@provinceId, N'Şereflikoçhisar'),
    (@provinceId, N'Yenimahalle');
GO

-- 7 Antalya
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 7);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Akseki'),
    (@provinceId, N'Aksu'),
    (@provinceId, N'Alanya'),
    (@provinceId, N'Demre'),
    (@provinceId, N'Döşemealtı'),
    (@provinceId, N'Elmalı'),
    (@provinceId, N'Finike'),
    (@provinceId, N'Gazipaşa'),
    (@provinceId, N'Gündoğmuş'),
    (@provinceId, N'İbradı'),
    (@provinceId, N'Kaş'),
    (@provinceId, N'Kemer'),
    (@provinceId, N'Kepez'),
    (@provinceId, N'Konyaaltı'),
    (@provinceId, N'Korkuteli'),
    (@provinceId, N'Kumluca'),
    (@provinceId, N'Manavgat'),
    (@provinceId, N'Muratpaşa'),
    (@provinceId, N'Serik');
GO

-- 8 Artvin
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 8);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Merkez'),
    (@provinceId, N'Ardanuç'),
    (@provinceId, N'Arhavi'),
    (@provinceId, N'Borçka'),
    (@provinceId, N'Hopa'),
    (@provinceId, N'Murgul'),
    (@provinceId, N'Şavşat'),
    (@provinceId, N'Yusufeli');
GO

-- 9 Aydın
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 9);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Efeler'),
    (@provinceId, N'Bozdoğan'),
    (@provinceId, N'Buharkent'),
    (@provinceId, N'Çine'),
    (@provinceId, N'Didim'),
    (@provinceId, N'Germencik'),
    (@provinceId, N'İncirliova'),
    (@provinceId, N'Karacasu'),
    (@provinceId, N'Karpuzlu'),
    (@provinceId, N'Koçarlı'),
    (@provinceId, N'Köşk'),
    (@provinceId, N'Kuşadası'),
    (@provinceId, N'Kuyucak'),
    (@provinceId, N'Nazilli'),
    (@provinceId, N'Söke'),
    (@provinceId, N'Sultanhisar'),
    (@provinceId, N'Yenipazar');
GO

-- 10 Balıkesir
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 10);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Altıeylül'),
    (@provinceId, N'Karesi'),
    (@provinceId, N'Ayvalık'),
    (@provinceId, N'Balya'),
    (@provinceId, N'Bandırma'),
    (@provinceId, N'Bigadiç'),
    (@provinceId, N'Burhaniye'),
    (@provinceId, N'Dursunbey'),
    (@provinceId, N'Edremit'),
    (@provinceId, N'Erdek'),
    (@provinceId, N'Gömeç'),
    (@provinceId, N'Gönen'),
    (@provinceId, N'Havran'),
    (@provinceId, N'İvrindi'),
    (@provinceId, N'Kepsut'),
    (@provinceId, N'Manyas'),
    (@provinceId, N'Marmara'),
    (@provinceId, N'Savaştepe'),
    (@provinceId, N'Sındırgı'),
    (@provinceId, N'Susurluk');
GO

-- 11 Bilecik
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 11);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Merkez'),
    (@provinceId, N'Bozüyük'),
    (@provinceId, N'Gölpazarı'),
    (@provinceId, N'İnhisar'),
    (@provinceId, N'Osmaneli'),
    (@provinceId, N'Pazaryeri'),
    (@provinceId, N'Söğüt'),
    (@provinceId, N'Yenipazar');
GO

-- 12 Bingöl
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 12);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Merkez'),
    (@provinceId, N'Adaklı'),
    (@provinceId, N'Genç'),
    (@provinceId, N'Karlıova'),
    (@provinceId, N'Kiğı'),
    (@provinceId, N'Solhan'),
    (@provinceId, N'Yayladere'),
    (@provinceId, N'Yedisu');
GO

-- 13 Bitlis
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 13);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Merkez'),
    (@provinceId, N'Adilcevaz'),
    (@provinceId, N'Ahlat'),
    (@provinceId, N'Güroymak'),
    (@provinceId, N'Hizan'),
    (@provinceId, N'Mutki'),
    (@provinceId, N'Tatvan');
GO

-- 14 Bolu
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 14);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Merkez'),
    (@provinceId, N'Dörtdivan'),
    (@provinceId, N'Gerede'),
    (@provinceId, N'Göynük'),
    (@provinceId, N'Kıbrıscık'),
    (@provinceId, N'Mengen'),
    (@provinceId, N'Mudurnu'),
    (@provinceId, N'Seben'),
    (@provinceId, N'Yeniçağa');
GO

-- 15 Burdur
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 15);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Merkez'),
    (@provinceId, N'Ağlasun'),
    (@provinceId, N'Altınyayla'),
    (@provinceId, N'Bucak'),
    (@provinceId, N'Çavdır'),
    (@provinceId, N'Çeltikçi'),
    (@provinceId, N'Gölhisar'),
    (@provinceId, N'Karamanlı'),
    (@provinceId, N'Kemer'),
    (@provinceId, N'Tefenni'),
    (@provinceId, N'Yeşilova');
GO

-- 16 Bursa
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 16);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Osmangazi'),
    (@provinceId, N'Nilüfer'),
    (@provinceId, N'Yıldırım'),
    (@provinceId, N'Gemlik'),
    (@provinceId, N'Gürsu'),
    (@provinceId, N'Harmancık'),
    (@provinceId, N'İnegöl'),
    (@provinceId, N'İznik'),
    (@provinceId, N'Karacabey'),
    (@provinceId, N'Keles'),
    (@provinceId, N'Kestel'),
    (@provinceId, N'Mudanya'),
    (@provinceId, N'Mustafakemalpaşa'),
    (@provinceId, N'Orhaneli'),
    (@provinceId, N'Orhangazi'),
    (@provinceId, N'Yenişehir');
GO

-- 17 Çanakkale
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 17);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Merkez'),
    (@provinceId, N'Ayvacık'),
    (@provinceId, N'Bayramiç'),
    (@provinceId, N'Biga'),
    (@provinceId, N'Bozcaada'),
    (@provinceId, N'Çan'),
    (@provinceId, N'Eceabat'),
    (@provinceId, N'Ezine'),
    (@provinceId, N'Gelibolu'),
    (@provinceId, N'Gökçeada'),
    (@provinceId, N'Lapseki'),
    (@provinceId, N'Yenice');
GO

-- 18 Çankırı
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 18);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Merkez'),
    (@provinceId, N'Atkaracalar'),
    (@provinceId, N'Bayramören'),
    (@provinceId, N'Çerkeş'),
    (@provinceId, N'Eldivan'),
    (@provinceId, N'Ilgaz'),
    (@provinceId, N'Kızılırmak'),
    (@provinceId, N'Korgun'),
    (@provinceId, N'Kurşunlu'),
    (@provinceId, N'Orta'),
    (@provinceId, N'Şabanözü'),
    (@provinceId, N'Yapraklı');
GO

-- 19 Çorum
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 19);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Merkez'),
    (@provinceId, N'Alaca'),
    (@provinceId, N'Bayat'),
    (@provinceId, N'Boğazkale'),
    (@provinceId, N'Dodurga'),
    (@provinceId, N'İskilip'),
    (@provinceId, N'Kargı'),
    (@provinceId, N'Laçin'),
    (@provinceId, N'Mecitözü'),
    (@provinceId, N'Oğuzlar'),
    (@provinceId, N'Ortaköy'),
    (@provinceId, N'Osmancık'),
    (@provinceId, N'Sungurlu'),
    (@provinceId, N'Uğurludağ');
GO

-- 20 Denizli
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 20);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Pamukkale'),
    (@provinceId, N'Merkezefendi'),
    (@provinceId, N'Acıpayam'),
    (@provinceId, N'Babadağ'),
    (@provinceId, N'Baklan'),
    (@provinceId, N'Bekilli'),
    (@provinceId, N'Beyağaç'),
    (@provinceId, N'Bozkurt'),
    (@provinceId, N'Buldan'),
    (@provinceId, N'Çal'),
    (@provinceId, N'Çameli'),
    (@provinceId, N'Çardak'),
    (@provinceId, N'Çivril'),
    (@provinceId, N'Güney'),
    (@provinceId, N'Honaz'),
    (@provinceId, N'Kale'),
    (@provinceId, N'Sarayköy'),
    (@provinceId, N'Serinhisar'),
    (@provinceId, N'Tavas');
GO

-- 21 Diyarbakır
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 21);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Bağlar'),
    (@provinceId, N'Kayapınar'),
    (@provinceId, N'Sur'),
    (@provinceId, N'Yenişehir'),
    (@provinceId, N'Bismil'),
    (@provinceId, N'Çermik'),
    (@provinceId, N'Çınar'),
    (@provinceId, N'Çüngüş'),
    (@provinceId, N'Dicle'),
    (@provinceId, N'Eğil'),
    (@provinceId, N'Ergani'),
    (@provinceId, N'Hani'),
    (@provinceId, N'Hazro'),
    (@provinceId, N'Kocaköy'),
    (@provinceId, N'Kulp'),
    (@provinceId, N'Lice'),
    (@provinceId, N'Silvan');
GO

-- 22 Edirne
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 22);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Merkez'),
    (@provinceId, N'Enez'),
    (@provinceId, N'Havsa'),
    (@provinceId, N'İpsala'),
    (@provinceId, N'Keşan'),
    (@provinceId, N'Lalapaşa'),
    (@provinceId, N'Meriç'),
    (@provinceId, N'Süloğlu'),
    (@provinceId, N'Uzunköprü');
GO

-- 23 Elazığ
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 23);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Merkez'),
    (@provinceId, N'Ağın'),
    (@provinceId, N'Alacakaya'),
    (@provinceId, N'Arıcak'),
    (@provinceId, N'Baskil'),
    (@provinceId, N'Karakoçan'),
    (@provinceId, N'Keban'),
    (@provinceId, N'Kovancılar'),
    (@provinceId, N'Maden'),
    (@provinceId, N'Palu'),
    (@provinceId, N'Sivrice');
GO

-- 24 Erzincan
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 24);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Merkez'),
    (@provinceId, N'Çayırlı'),
    (@provinceId, N'İliç'),
    (@provinceId, N'Kemah'),
    (@provinceId, N'Kemaliye'),
    (@provinceId, N'Otlukbeli'),
    (@provinceId, N'Refahiye'),
    (@provinceId, N'Tercan'),
    (@provinceId, N'Üzümlü');
GO

-- 25 Erzurum
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 25);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Aziziye'),
    (@provinceId, N'Palandöken'),
    (@provinceId, N'Yakutiye'),
    (@provinceId, N'Aşkale'),
    (@provinceId, N'Çat'),
    (@provinceId, N'Hınıs'),
    (@provinceId, N'Horasan'),
    (@provinceId, N'İspir'),
    (@provinceId, N'Karaçoban'),
    (@provinceId, N'Karayazı'),
    (@provinceId, N'Köprüköy'),
    (@provinceId, N'Narman'),
    (@provinceId, N'Oltu'),
    (@provinceId, N'Olur'),
    (@provinceId, N'Pasinler'),
    (@provinceId, N'Pazaryolu'),
    (@provinceId, N'Şenkaya'),
    (@provinceId, N'Tekman'),
    (@provinceId, N'Tortum'),
    (@provinceId, N'Uzundere');
GO

-- 26 Eskişehir
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 26);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Odunpazarı'),
    (@provinceId, N'Tepebaşı'),
    (@provinceId, N'Alpu'),
    (@provinceId, N'Beylikova'),
    (@provinceId, N'Çifteler'),
    (@provinceId, N'Günyüzü'),
    (@provinceId, N'Han'),
    (@provinceId, N'İnönü'),
    (@provinceId, N'Mahmudiye'),
    (@provinceId, N'Mihalgazi'),
    (@provinceId, N'Mihalıççık'),
    (@provinceId, N'Sarıcakaya'),
    (@provinceId, N'Seyitgazi'),
    (@provinceId, N'Sivrihisar');
GO

-- 27 Gaziantep
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 27);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Şahinbey'),
    (@provinceId, N'Şehitkamil'),
    (@provinceId, N'Araban'),
    (@provinceId, N'İslahiye'),
    (@provinceId, N'Karkamış'),
    (@provinceId, N'Nizip'),
    (@provinceId, N'Nurdağı'),
    (@provinceId, N'Oğuzeli'),
    (@provinceId, N'Yavuzeli');
GO

-- 28 Giresun
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 28);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Merkez'),
    (@provinceId, N'Alucra'),
    (@provinceId, N'Bulancak'),
    (@provinceId, N'Çamoluk'),
    (@provinceId, N'Çanakçı'),
    (@provinceId, N'Dereli'),
    (@provinceId, N'Doğankent'),
    (@provinceId, N'Espiye'),
    (@provinceId, N'Eynesil'),
    (@provinceId, N'Görele'),
    (@provinceId, N'Güce'),
    (@provinceId, N'Keşap'),
    (@provinceId, N'Piraziz'),
    (@provinceId, N'Şebinkarahisar'),
    (@provinceId, N'Tirebolu'),
    (@provinceId, N'Yağlıdere');
GO

-- 29 Gümüşhane
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 29);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Merkez'),
    (@provinceId, N'Kelkit'),
    (@provinceId, N'Köse'),
    (@provinceId, N'Kürtün'),
    (@provinceId, N'Şiran'),
    (@provinceId, N'Torul');
GO

-- 30 Hakkari
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 30);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Merkez'),
    (@provinceId, N'Çukurca'),
    (@provinceId, N'Şemdinli'),
    (@provinceId, N'Yüksekova');
GO

-- 31 Hatay
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 31);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Antakya'),
    (@provinceId, N'Defne'),
    (@provinceId, N'Arsuz'),
    (@provinceId, N'Altınözü'),
    (@provinceId, N'Belen'),
    (@provinceId, N'Dörtyol'),
    (@provinceId, N'Erzin'),
    (@provinceId, N'Hassa'),
    (@provinceId, N'İskenderun'),
    (@provinceId, N'Kırıkhan'),
    (@provinceId, N'Kumlu'),
    (@provinceId, N'Payas'),
    (@provinceId, N'Reyhanlı'),
    (@provinceId, N'Samandağ'),
    (@provinceId, N'Yayladağı');
GO

-- 32 Isparta
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 32);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Merkez'),
    (@provinceId, N'Aksu'),
    (@provinceId, N'Atabey'),
    (@provinceId, N'Eğirdir'),
    (@provinceId, N'Gelendost'),
    (@provinceId, N'Gönen'),
    (@provinceId, N'Keçiborlu'),
    (@provinceId, N'Senirkent'),
    (@provinceId, N'Sütçüler'),
    (@provinceId, N'Şarkikaraağaç'),
    (@provinceId, N'Uluborlu'),
    (@provinceId, N'Yalvaç'),
    (@provinceId, N'Yenişarbademli');
GO

-- 33 Mersin
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 33);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Akdeniz'),
    (@provinceId, N'Mezitli'),
    (@provinceId, N'Toroslar'),
    (@provinceId, N'Yenişehir'),
    (@provinceId, N'Anamur'),
    (@provinceId, N'Aydıncık'),
    (@provinceId, N'Bozyazı'),
    (@provinceId, N'Çamlıyayla'),
    (@provinceId, N'Erdemli'),
    (@provinceId, N'Gülnar'),
    (@provinceId, N'Mut'),
    (@provinceId, N'Silifke'),
    (@provinceId, N'Tarsus');
GO

-- 34 İstanbul
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 34);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Adalar'),
    (@provinceId, N'Arnavutköy'),
    (@provinceId, N'Ataşehir'),
    (@provinceId, N'Avcılar'),
    (@provinceId, N'Bağcılar'),
    (@provinceId, N'Bahçelievler'),
    (@provinceId, N'Bakırköy'),
    (@provinceId, N'Başakşehir'),
    (@provinceId, N'Bayrampaşa'),
    (@provinceId, N'Beşiktaş'),
    (@provinceId, N'Beykoz'),
    (@provinceId, N'Beylikdüzü'),
    (@provinceId, N'Beyoğlu'),
    (@provinceId, N'Büyükçekmece'),
    (@provinceId, N'Çatalca'),
    (@provinceId, N'Çekmeköy'),
    (@provinceId, N'Esenler'),
    (@provinceId, N'Esenyurt'),
    (@provinceId, N'Eyüpsultan'),
    (@provinceId, N'Fatih'),
    (@provinceId, N'Gaziosmanpaşa'),
    (@provinceId, N'Güngören'),
    (@provinceId, N'Kadıköy'),
    (@provinceId, N'Kağıthane'),
    (@provinceId, N'Kartal'),
    (@provinceId, N'Küçükçekmece'),
    (@provinceId, N'Maltepe'),
    (@provinceId, N'Pendik'),
    (@provinceId, N'Sancaktepe'),
    (@provinceId, N'Sarıyer'),
    (@provinceId, N'Silivri'),
    (@provinceId, N'Sultanbeyli'),
    (@provinceId, N'Sultangazi'),
    (@provinceId, N'Şile'),
    (@provinceId, N'Şişli'),
    (@provinceId, N'Tuzla'),
    (@provinceId, N'Ümraniye'),
    (@provinceId, N'Üsküdar'),
    (@provinceId, N'Zeytinburnu');
GO

-- 35 İzmir
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 35);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Aliağa'),
    (@provinceId, N'Balçova'),
    (@provinceId, N'Bayındır'),
    (@provinceId, N'Bayraklı'),
    (@provinceId, N'Bergama'),
    (@provinceId, N'Beydağ'),
    (@provinceId, N'Bornova'),
    (@provinceId, N'Buca'),
    (@provinceId, N'Çeşme'),
    (@provinceId, N'Çiğli'),
    (@provinceId, N'Dikili'),
    (@provinceId, N'Foça'),
    (@provinceId, N'Gaziemir'),
    (@provinceId, N'Güzelbahçe'),
    (@provinceId, N'Karabağlar'),
    (@provinceId, N'Karaburun'),
    (@provinceId, N'Karşıyaka'),
    (@provinceId, N'Kemalpaşa'),
    (@provinceId, N'Kınık'),
    (@provinceId, N'Kiraz'),
    (@provinceId, N'Konak'),
    (@provinceId, N'Menderes'),
    (@provinceId, N'Menemen'),
    (@provinceId, N'Narlıdere'),
    (@provinceId, N'Ödemiş'),
    (@provinceId, N'Seferihisar'),
    (@provinceId, N'Selçuk'),
    (@provinceId, N'Tire'),
    (@provinceId, N'Torbalı'),
    (@provinceId, N'Urla');
GO

-- 36 Kars
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 36);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Merkez'),
    (@provinceId, N'Akyaka'),
    (@provinceId, N'Arpaçay'),
    (@provinceId, N'Digor'),
    (@provinceId, N'Kağızman'),
    (@provinceId, N'Sarıkamış'),
    (@provinceId, N'Selim'),
    (@provinceId, N'Susuz');
GO

-- 37 Kastamonu
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 37);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Merkez'),
    (@provinceId, N'Abana'),
    (@provinceId, N'Ağlı'),
    (@provinceId, N'Araç'),
    (@provinceId, N'Azdavay'),
    (@provinceId, N'Bozkurt'),
    (@provinceId, N'Cide'),
    (@provinceId, N'Çatalzeytin'),
    (@provinceId, N'Daday'),
    (@provinceId, N'Devrekani'),
    (@provinceId, N'Doğanyurt'),
    (@provinceId, N'Hanönü'),
    (@provinceId, N'İhsangazi'),
    (@provinceId, N'İnebolu'),
    (@provinceId, N'Küre'),
    (@provinceId, N'Pınarbaşı'),
    (@provinceId, N'Seydiler'),
    (@provinceId, N'Şenpazar'),
    (@provinceId, N'Taşköprü'),
    (@provinceId, N'Tosya');
GO

-- 38 Kayseri
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 38);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Kocasinan'),
    (@provinceId, N'Melikgazi'),
    (@provinceId, N'Talas'),
    (@provinceId, N'Akkışla'),
    (@provinceId, N'Bünyan'),
    (@provinceId, N'Develi'),
    (@provinceId, N'Felahiye'),
    (@provinceId, N'Hacılar'),
    (@provinceId, N'İncesu'),
    (@provinceId, N'Özvatan'),
    (@provinceId, N'Pınarbaşı'),
    (@provinceId, N'Sarıoğlan'),
    (@provinceId, N'Sarız'),
    (@provinceId, N'Tomarza'),
    (@provinceId, N'Yahyalı'),
    (@provinceId, N'Yeşilhisar');
GO

-- 39 Kırklareli
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 39);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Merkez'),
    (@provinceId, N'Babaeski'),
    (@provinceId, N'Demirköy'),
    (@provinceId, N'Kofçaz'),
    (@provinceId, N'Lüleburgaz'),
    (@provinceId, N'Pehlivanköy'),
    (@provinceId, N'Pınarhisar'),
    (@provinceId, N'Vize');
GO

-- 40 Kırşehir
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 40);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Merkez'),
    (@provinceId, N'Akçakent'),
    (@provinceId, N'Akpınar'),
    (@provinceId, N'Boztepe'),
    (@provinceId, N'Çiçekdağı'),
    (@provinceId, N'Kaman'),
    (@provinceId, N'Mucur');
GO

-- 41 Kocaeli
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 41);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'İzmit'),
    (@provinceId, N'Başiskele'),
    (@provinceId, N'Çayırova'),
    (@provinceId, N'Darıca'),
    (@provinceId, N'Derince'),
    (@provinceId, N'Dilovası'),
    (@provinceId, N'Gebze'),
    (@provinceId, N'Gölcük'),
    (@provinceId, N'Kandıra'),
    (@provinceId, N'Karamürsel'),
    (@provinceId, N'Kartepe'),
    (@provinceId, N'Körfez');
GO

-- 42 Konya
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 42);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Selçuklu'),
    (@provinceId, N'Meram'),
    (@provinceId, N'Karatay'),
    (@provinceId, N'Ahırlı'),
    (@provinceId, N'Akören'),
    (@provinceId, N'Akşehir'),
    (@provinceId, N'Altınekin'),
    (@provinceId, N'Beyşehir'),
    (@provinceId, N'Bozkır'),
    (@provinceId, N'Cihanbeyli'),
    (@provinceId, N'Çeltik'),
    (@provinceId, N'Çumra'),
    (@provinceId, N'Derbent'),
    (@provinceId, N'Derebucak'),
    (@provinceId, N'Doğanhisar'),
    (@provinceId, N'Emirgazi'),
    (@provinceId, N'Ereğli'),
    (@provinceId, N'Güneysınır'),
    (@provinceId, N'Hadim'),
    (@provinceId, N'Halkapınar'),
    (@provinceId, N'Hüyük'),
    (@provinceId, N'Ilgın'),
    (@provinceId, N'Kadınhanı'),
    (@provinceId, N'Karapınar'),
    (@provinceId, N'Kulu'),
    (@provinceId, N'Sarayönü'),
    (@provinceId, N'Seydişehir'),
    (@provinceId, N'Taşkent'),
    (@provinceId, N'Tuzlukçu'),
    (@provinceId, N'Yalıhüyük'),
    (@provinceId, N'Yunak');
GO

-- 43 Kütahya
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 43);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Merkez'),
    (@provinceId, N'Altıntaş'),
    (@provinceId, N'Aslanapa'),
    (@provinceId, N'Çavdarhisar'),
    (@provinceId, N'Domaniç'),
    (@provinceId, N'Dumlupınar'),
    (@provinceId, N'Emet'),
    (@provinceId, N'Gediz'),
    (@provinceId, N'Hisarcık'),
    (@provinceId, N'Pazarlar'),
    (@provinceId, N'Simav'),
    (@provinceId, N'Şaphane'),
    (@provinceId, N'Tavşanlı');
GO

-- 44 Malatya
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 44);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Battalgazi'),
    (@provinceId, N'Yeşilyurt'),
    (@provinceId, N'Akçadağ'),
    (@provinceId, N'Arapgir'),
    (@provinceId, N'Arguvan'),
    (@provinceId, N'Darende'),
    (@provinceId, N'Doğanşehir'),
    (@provinceId, N'Doğanyol'),
    (@provinceId, N'Hekimhan'),
    (@provinceId, N'Kale'),
    (@provinceId, N'Kuluncak'),
    (@provinceId, N'Pütürge'),
    (@provinceId, N'Yazıhan');
GO

-- 45 Manisa
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 45);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Şehzadeler'),
    (@provinceId, N'Yunusemre'),
    (@provinceId, N'Ahmetli'),
    (@provinceId, N'Akhisar'),
    (@provinceId, N'Alaşehir'),
    (@provinceId, N'Demirci'),
    (@provinceId, N'Gölmarmara'),
    (@provinceId, N'Gördes'),
    (@provinceId, N'Kırkağaç'),
    (@provinceId, N'Köprübaşı'),
    (@provinceId, N'Kula'),
    (@provinceId, N'Salihli'),
    (@provinceId, N'Sarıgöl'),
    (@provinceId, N'Saruhanlı'),
    (@provinceId, N'Selendi'),
    (@provinceId, N'Soma'),
    (@provinceId, N'Turgutlu');
GO

-- 46 Kahramanmaraş
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 46);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Onikişubat'),
    (@provinceId, N'Dulkadiroğlu'),
    (@provinceId, N'Afşin'),
    (@provinceId, N'Andırın'),
    (@provinceId, N'Çağlayancerit'),
    (@provinceId, N'Ekinözü'),
    (@provinceId, N'Elbistan'),
    (@provinceId, N'Göksun'),
    (@provinceId, N'Nurhak'),
    (@provinceId, N'Pazarcık'),
    (@provinceId, N'Türkoğlu');
GO

-- 47 Mardin
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 47);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Artuklu'),
    (@provinceId, N'Dargeçit'),
    (@provinceId, N'Derik'),
    (@provinceId, N'Kızıltepe'),
    (@provinceId, N'Mazıdağı'),
    (@provinceId, N'Midyat'),
    (@provinceId, N'Nusaybin'),
    (@provinceId, N'Ömerli'),
    (@provinceId, N'Savur'),
    (@provinceId, N'Yeşilli');
GO

-- 48 Muğla
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 48);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Menteşe'),
    (@provinceId, N'Bodrum'),
    (@provinceId, N'Dalaman'),
    (@provinceId, N'Datça'),
    (@provinceId, N'Fethiye'),
    (@provinceId, N'Kavaklıdere'),
    (@provinceId, N'Köyceğiz'),
    (@provinceId, N'Marmaris'),
    (@provinceId, N'Milas'),
    (@provinceId, N'Ortaca'),
    (@provinceId, N'Seydikemer'),
    (@provinceId, N'Ula'),
    (@provinceId, N'Yatağan');
GO

-- 49 Muş
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 49);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Merkez'),
    (@provinceId, N'Bulanık'),
    (@provinceId, N'Hasköy'),
    (@provinceId, N'Korkut'),
    (@provinceId, N'Malazgirt'),
    (@provinceId, N'Varto');
GO

-- 50 Nevşehir
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 50);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Merkez'),
    (@provinceId, N'Acıgöl'),
    (@provinceId, N'Avanos'),
    (@provinceId, N'Derinkuyu'),
    (@provinceId, N'Gülşehir'),
    (@provinceId, N'Hacıbektaş'),
    (@provinceId, N'Kozaklı'),
    (@provinceId, N'Ürgüp');
GO

-- 51 Niğde
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 51);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Merkez'),
    (@provinceId, N'Altunhisar'),
    (@provinceId, N'Bor'),
    (@provinceId, N'Çamardı'),
    (@provinceId, N'Çiftlik'),
    (@provinceId, N'Ulukışla');
GO

-- 52 Ordu
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 52);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Altınordu'),
    (@provinceId, N'Akkuş'),
    (@provinceId, N'Aybastı'),
    (@provinceId, N'Çamaş'),
    (@provinceId, N'Çatalpınar'),
    (@provinceId, N'Çaybaşı'),
    (@provinceId, N'Fatsa'),
    (@provinceId, N'Gölköy'),
    (@provinceId, N'Gülyalı'),
    (@provinceId, N'Gürgentepe'),
    (@provinceId, N'İkizce'),
    (@provinceId, N'Kabadüz'),
    (@provinceId, N'Kabataş'),
    (@provinceId, N'Korgan'),
    (@provinceId, N'Kumru'),
    (@provinceId, N'Mesudiye'),
    (@provinceId, N'Perşembe'),
    (@provinceId, N'Ulubey'),
    (@provinceId, N'Ünye');
GO

-- 53 Rize
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 53);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Merkez'),
    (@provinceId, N'Ardeşen'),
    (@provinceId, N'Çamlıhemşin'),
    (@provinceId, N'Çayeli'),
    (@provinceId, N'Derepazarı'),
    (@provinceId, N'Fındıklı'),
    (@provinceId, N'Güneysu'),
    (@provinceId, N'Hemşin'),
    (@provinceId, N'İkizdere'),
    (@provinceId, N'İyidere'),
    (@provinceId, N'Kalkandere'),
    (@provinceId, N'Pazar');
GO

-- 54 Sakarya
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 54);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Adapazarı'),
    (@provinceId, N'Akyazı'),
    (@provinceId, N'Arifiye'),
    (@provinceId, N'Erenler'),
    (@provinceId, N'Ferizli'),
    (@provinceId, N'Geyve'),
    (@provinceId, N'Hendek'),
    (@provinceId, N'Karapürçek'),
    (@provinceId, N'Karasu'),
    (@provinceId, N'Kaynarca'),
    (@provinceId, N'Kocaali'),
    (@provinceId, N'Pamukova'),
    (@provinceId, N'Sapanca'),
    (@provinceId, N'Serdivan'),
    (@provinceId, N'Söğütlü'),
    (@provinceId, N'Taraklı');
GO

-- 55 Samsun
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 55);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'İlkadım'),
    (@provinceId, N'Atakum'),
    (@provinceId, N'Canik'),
    (@provinceId, N'Alaçam'),
    (@provinceId, N'Asarcık'),
    (@provinceId, N'Ayvacık'),
    (@provinceId, N'Bafra'),
    (@provinceId, N'Çarşamba'),
    (@provinceId, N'Havza'),
    (@provinceId, N'Kavak'),
    (@provinceId, N'Ladik'),
    (@provinceId, N'Salıpazarı'),
    (@provinceId, N'Tekkeköy'),
    (@provinceId, N'Terme'),
    (@provinceId, N'Vezirköprü'),
    (@provinceId, N'Yakakent'),
    (@provinceId, N'19 Mayıs');
GO

-- 56 Siirt
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 56);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Merkez'),
    (@provinceId, N'Baykan'),
    (@provinceId, N'Eruh'),
    (@provinceId, N'Kurtalan'),
    (@provinceId, N'Pervari'),
    (@provinceId, N'Şirvan'),
    (@provinceId, N'Tillo');
GO

-- 57 Sinop
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 57);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Merkez'),
    (@provinceId, N'Ayancık'),
    (@provinceId, N'Boyabat'),
    (@provinceId, N'Dikmen'),
    (@provinceId, N'Durağan'),
    (@provinceId, N'Erfelek'),
    (@provinceId, N'Gerze'),
    (@provinceId, N'Saraydüzü'),
    (@provinceId, N'Türkeli');
GO

-- 58 Sivas
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 58);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Merkez'),
    (@provinceId, N'Akıncılar'),
    (@provinceId, N'Altınyayla'),
    (@provinceId, N'Divriği'),
    (@provinceId, N'Doğanşar'),
    (@provinceId, N'Gemerek'),
    (@provinceId, N'Gölova'),
    (@provinceId, N'Gürün'),
    (@provinceId, N'Hafik'),
    (@provinceId, N'İmranlı'),
    (@provinceId, N'Kangal'),
    (@provinceId, N'Koyulhisar'),
    (@provinceId, N'Suşehri'),
    (@provinceId, N'Şarkışla'),
    (@provinceId, N'Ulaş'),
    (@provinceId, N'Yıldızeli'),
    (@provinceId, N'Zara');
GO

-- 59 Tekirdağ
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 59);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Süleymanpaşa'),
    (@provinceId, N'Çerkezköy'),
    (@provinceId, N'Çorlu'),
    (@provinceId, N'Ergene'),
    (@provinceId, N'Hayrabolu'),
    (@provinceId, N'Kapaklı'),
    (@provinceId, N'Malkara'),
    (@provinceId, N'Marmaraereğlisi'),
    (@provinceId, N'Muratlı'),
    (@provinceId, N'Saray'),
    (@provinceId, N'Şarköy');
GO

-- 60 Tokat
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 60);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Merkez'),
    (@provinceId, N'Almus'),
    (@provinceId, N'Artova'),
    (@provinceId, N'Başçiftlik'),
    (@provinceId, N'Erbaa'),
    (@provinceId, N'Niksar'),
    (@provinceId, N'Pazar'),
    (@provinceId, N'Reşadiye'),
    (@provinceId, N'Sulusaray'),
    (@provinceId, N'Turhal'),
    (@provinceId, N'Yeşilyurt'),
    (@provinceId, N'Zile');
GO

-- 61 Trabzon
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 61);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Ortahisar'),
    (@provinceId, N'Akçaabat'),
    (@provinceId, N'Araklı'),
    (@provinceId, N'Arsin'),
    (@provinceId, N'Beşikdüzü'),
    (@provinceId, N'Çarşıbaşı'),
    (@provinceId, N'Çaykara'),
    (@provinceId, N'Dernekpazarı'),
    (@provinceId, N'Düzköy'),
    (@provinceId, N'Hayrat'),
    (@provinceId, N'Köprübaşı'),
    (@provinceId, N'Maçka'),
    (@provinceId, N'Of'),
    (@provinceId, N'Sürmene'),
    (@provinceId, N'Şalpazarı'),
    (@provinceId, N'Tonya'),
    (@provinceId, N'Vakfıkebir'),
    (@provinceId, N'Yomra');
GO

-- 62 Tunceli
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 62);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Merkez'),
    (@provinceId, N'Çemişgezek'),
    (@provinceId, N'Hozat'),
    (@provinceId, N'Mazgirt'),
    (@provinceId, N'Nazımiye'),
    (@provinceId, N'Ovacık'),
    (@provinceId, N'Pertek'),
    (@provinceId, N'Pülümür');
GO

-- 63 Şanlıurfa
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 63);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Eyyübiye'),
    (@provinceId, N'Haliliye'),
    (@provinceId, N'Karaköprü'),
    (@provinceId, N'Akçakale'),
    (@provinceId, N'Birecik'),
    (@provinceId, N'Bozova'),
    (@provinceId, N'Ceylanpınar'),
    (@provinceId, N'Halfeti'),
    (@provinceId, N'Harran'),
    (@provinceId, N'Hilvan'),
    (@provinceId, N'Siverek'),
    (@provinceId, N'Suruç'),
    (@provinceId, N'Viranşehir');
GO

-- 64 Uşak
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 64);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Merkez'),
    (@provinceId, N'Banaz'),
    (@provinceId, N'Eşme'),
    (@provinceId, N'Karahallı'),
    (@provinceId, N'Sivaslı'),
    (@provinceId, N'Ulubey');
GO

-- 65 Van
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 65);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'İpekyolu'),
    (@provinceId, N'Edremit'),
    (@provinceId, N'Tuşba'),
    (@provinceId, N'Bahçesaray'),
    (@provinceId, N'Başkale'),
    (@provinceId, N'Çaldıran'),
    (@provinceId, N'Çatak'),
    (@provinceId, N'Erciş'),
    (@provinceId, N'Gevaş'),
    (@provinceId, N'Gürpınar'),
    (@provinceId, N'Muradiye'),
    (@provinceId, N'Özalp'),
    (@provinceId, N'Saray');
GO

-- 66 Yozgat
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 66);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Merkez'),
    (@provinceId, N'Akdağmadeni'),
    (@provinceId, N'Aydıncık'),
    (@provinceId, N'Boğazlıyan'),
    (@provinceId, N'Çandır'),
    (@provinceId, N'Çayıralan'),
    (@provinceId, N'Çekerek'),
    (@provinceId, N'Kadışehri'),
    (@provinceId, N'Saraykent'),
    (@provinceId, N'Sarıkaya'),
    (@provinceId, N'Sorgun'),
    (@provinceId, N'Şefaatli'),
    (@provinceId, N'Yenifakılı'),
    (@provinceId, N'Yerköy');
GO

-- 67 Zonguldak
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 67);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Merkez'),
    (@provinceId, N'Alaplı'),
    (@provinceId, N'Çaycuma'),
    (@provinceId, N'Devrek'),
    (@provinceId, N'Ereğli'),
    (@provinceId, N'Gökçebey');
GO

-- 68 Aksaray
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 68);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Merkez'),
    (@provinceId, N'Ağaçören'),
    (@provinceId, N'Eskil'),
    (@provinceId, N'Gülağaç'),
    (@provinceId, N'Güzelyurt'),
    (@provinceId, N'Ortaköy'),
    (@provinceId, N'Sarıyahşi');
GO

-- 69 Bayburt
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 69);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Merkez'),
    (@provinceId, N'Aydıntepe'),
    (@provinceId, N'Demirözü');
GO

-- 70 Karaman
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 70);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Merkez'),
    (@provinceId, N'Ayrancı'),
    (@provinceId, N'Başyayla'),
    (@provinceId, N'Ermenek'),
    (@provinceId, N'Kazımkarabekir'),
    (@provinceId, N'Sarıveliler');
GO

-- 71 Kırıkkale
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 71);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Merkez'),
    (@provinceId, N'Bahşili'),
    (@provinceId, N'Balışeyh'),
    (@provinceId, N'Çelebi'),
    (@provinceId, N'Delice'),
    (@provinceId, N'Karakeçili'),
    (@provinceId, N'Keskin'),
    (@provinceId, N'Sulakyurt'),
    (@provinceId, N'Yahşihan');
GO

-- 72 Batman
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 72);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Merkez'),
    (@provinceId, N'Beşiri'),
    (@provinceId, N'Gercüş'),
    (@provinceId, N'Hasankeyf'),
    (@provinceId, N'Kozluk'),
    (@provinceId, N'Sason');
GO

-- 73 Şırnak
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 73);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Merkez'),
    (@provinceId, N'Beytüşşebap'),
    (@provinceId, N'Cizre'),
    (@provinceId, N'Güçlükonak'),
    (@provinceId, N'İdil'),
    (@provinceId, N'Silopi'),
    (@provinceId, N'Uludere');
GO

-- 74 Bartın
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 74);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Merkez'),
    (@provinceId, N'Amasra'),
    (@provinceId, N'Kurucaşile'),
    (@provinceId, N'Ulus');
GO

-- 75 Ardahan
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 75);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Merkez'),
    (@provinceId, N'Çıldır'),
    (@provinceId, N'Damal'),
    (@provinceId, N'Göle'),
    (@provinceId, N'Hanak'),
    (@provinceId, N'Posof');
GO

-- 76 Iğdır
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 76);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Merkez'),
    (@provinceId, N'Aralık'),
    (@provinceId, N'Karakoyunlu'),
    (@provinceId, N'Tuzluca');
GO

-- 77 Yalova
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 77);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Merkez'),
    (@provinceId, N'Altınova'),
    (@provinceId, N'Armutlu'),
    (@provinceId, N'Çınarcık'),
    (@provinceId, N'Çiftlikköy'),
    (@provinceId, N'Termal');
GO

-- 78 Karabük
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 78);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Merkez'),
    (@provinceId, N'Eflani'),
    (@provinceId, N'Eskipazar'),
    (@provinceId, N'Ovacık'),
    (@provinceId, N'Safranbolu'),
    (@provinceId, N'Yenice');
GO

-- 79 Kilis
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 79);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Merkez'),
    (@provinceId, N'Elbeyli'),
    (@provinceId, N'Musabeyli'),
    (@provinceId, N'Polateli');
GO

-- 80 Osmaniye
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 80);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Merkez'),
    (@provinceId, N'Bahçe'),
    (@provinceId, N'Düziçi'),
    (@provinceId, N'Hasanbeyli'),
    (@provinceId, N'Kadirli'),
    (@provinceId, N'Sumbas'),
    (@provinceId, N'Toprakkale');
GO

-- 81 Düzce
DECLARE @provinceId UNIQUEIDENTIFIER = (SELECT id FROM dbo.Provinces WHERE plate_code = 81);
INSERT INTO dbo.Districts (province_id, name) VALUES
    (@provinceId, N'Merkez'),
    (@provinceId, N'Akçakoca'),
    (@provinceId, N'Cumayeri'),
    (@provinceId, N'Çilimli'),
    (@provinceId, N'Gölyaka'),
    (@provinceId, N'Gümüşova'),
    (@provinceId, N'Kaynaşlı'),
    (@provinceId, N'Yığılca');
GO

